[package]
name = "artifacts-mmo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
env_logger = "0.11.5"
# Logging
log = { version = "0.4.22", features = ["serde"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_bytes = "0.11.15"
serde_json = { version = "1.0.121" }
# Time
time = { version = "0.3.36", features = [
	"serde",
	"formatting",
	"std",
	"parsing",
] }
ureq = { version = "2.10.0", features = ["json", "cookies", "charset"] }
